ticket 4 first pr
EddySafc/eddy-porfoliio-project-fe pull request #2
Opened 2022-12-05 16:02 UTC by EddySafc

2022-12-05 16:16 UTC, callumu21 requested changes
Good start! Just a few notes:

1. Using CSS, you should remove the bullet points in the list view of reviews. 
2. There are some images not coming through, so maybe add an alt tag to the image display in case that happens.
3. You should think about using an isLoading state to give users feedback about when your list of reviews is being fetched.

2022-12-05 16:16 UTC, callumu21 commented on src/components/Reviews.jsx
> +    <section>
We should give users some visual feedback here for when the page is loading and waiting for the fetch request to complete.

2022-12-06 10:16 UTC, pkaodev commented on src/components/Reviews.jsx
> +                  alt="no image available"
no image available isn't super helpful.  Use some property that exists on the review.  What is the image meant to be portraying?

2022-12-06 10:17 UTC, pkaodev commented
Once you've updated the alt text feel free to merge.

2022-12-06 10:22 UTC, merged